image: Ubuntu1804 # образ для сборки

stack: node 16 # окружение

branches:
  only:
    - master # ветка git

cache: node_modules # кеширование

install:
  - npm cache clean --force
  - npm install # команда установки зависимостей
  - npm install pm2 -g

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build # команда сборки


